### ISSUE TITLE
Update scancode action to fix incorrect licensing errors

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/infrastructure#10]
Update the scancode action to fix incorrect licensing errors such as:

```
* scan/include/dt-bindings/pinctrl/samv71q-pinctrl.h is not bsd-x11 licensed: apache-2.0
* scan/include/dt-bindings/pinctrl/samv71q-pinctrl.h missing copyright.
```

For more details, see https://github.com/zephyrproject-rtos/hal_atmel/pull/19#issuecomment-1077815246.

**TODO**

- [x] Implement CI for `docker_scancode` repository (https://github.com/zephyrproject-rtos/docker-scancode/pull/4)
- [x] Merge https://github.com/zephyrproject-rtos/docker_scancode/pull/2
- [x] Merge https://github.com/zephyrproject-rtos/action_scancode/pull/13
- [x] Update all org-wide `action_scancode` usages
    - [x] zephyr (https://github.com/zephyrproject-rtos/zephyr/pull/44317)
    - [x] hal_atmel (https://github.com/zephyrproject-rtos/hal_atmel/pull/21)
    - [x] hal_quicklogic (https://github.com/zephyrproject-rtos/hal_quicklogic/pull/3)
    - [x] hal_xtensa (https://github.com/zephyrproject-rtos/hal_xtensa/pull/14)
