### ISSUE TITLE
Implement Terraform-based GitHub configuration

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/infrastructure#111]
## Summary

The goal of this task is to implement a set of Terraform manifests that define the GitHub teams and repositories in the `zephyrproject-rtos` organisation so that GitHub user permissions and repository configurations can be managed as "code."

This allows the changes to GitHub team membership and repository configurations to be made as "pull requests"; thereby,  being transparent, traceable and consistent (in contrast to multiple admins making random ad-hoc changes through the GitHub web UI).

## Tasks

Define and manage GitHub configurations and resources as Terraform manifests.

- [x] Implement team and member management
    - [x] Define GitHub teams in Terraform
    - [x] Define GitHub team memberships in Terraform
- [x] Implement repository and collaborator management proof-of-concept
    - [x] Implement a reference manifest defining basic GitHub repository configurations
    - [x] Implement a reference manifest defining branch protection rules
    - [x] Implement a reference manifest defining rulesets
- [ ] Define repository configurations in Terraform
    - [x] sdk-ng
    - [ ] zephyr
- [ ] Implement `MAINTAINERS.yml`-derived GitHub user access control automation
    - [x] Implement a script to synchronise the `collaborator` and `maintainer` team memberships with the Zephyr main repository `MAINTAINERS.yml`.
    - [x] Implement a script to synchronise the module repository collaborator list with the Zephyr main repository `MAINTAINERS.yml`.
    - [ ] Implement a GitHub Actions workflow to run the synchronisation scripts periodically and send pull requests if there are any changes.
