### ISSUE TITLE
Deploy zephyr-runner v2

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/infrastructure#152]
## Summary

This issue lists the specifications for the runner scale set-based zephyr-runner v2 and tracks its deployment process.

### Architecture

The Actions Runner Controller (ARC) shall be deployed in runner scale set mode using the Helm charts provided by GitHub:

* [gha-runner-scale-set-controller Helm Chart](https://github.com/actions/actions-runner-controller/pkgs/container/actions-runner-controller-charts%2Fgha-runner-scale-set-controller)
* [gha-runner-scale-set Helm Chart](https://github.com/actions/actions-runner-controller/pkgs/container/actions-runner-controller-charts%2Fgha-runner-scale-set)

The configurations for each Helm chart shall be provided in YAML format under `kubernetes/zephyr-runner-v2`, which shall be specified when installing the Helm charts.

Both the controller and individual runner scale set deployments shall strictly use Helm charts only, and no discrete Kubernetes resource manifest files shall be used -- this is to streamline deployment, maintenance and upgrade processes of the zephyr-runner v2.

The Helm chart installations shall be defined in the Terraform manifest files for each cloud and shall be deployed using Terraform -- this effectively allows the zephyr-runner v2 installations to be managed as individual resources in Terraform.

The cloud provider fail-over sequence shall be managed through the "apply" and "destroy" operations of the runner scale set Helm chart installation resources in Terraform -- i.e. OpenStack-to-AWS fail-over sequence shall destroy the runner scale set resources for OpenStack and apply the runner scale set resources for AWS.

The runner scale set deployments shall use "kubernetes" container mode, which runs the GitHub workflow job and service containers as Kubernetes native containers running in a "workflow pod" associated with the runner pod.

The CPU and RAM resource allocations shall be specified for the runner pod, and the workflow pod shall have a positive host affinity with the runner pod to ensure that it is scheduled onto the same node as the runner pod -- this ensures that the computing resources are properly balanced (because the GitHub Actions workflows actually run in the workflow pod and not runner pod).

The compute nodes for the AWS Kubernetes cluster shall be deployed in auto-scaling mode in an auto-scaling group that terminates idle nodes that are not executing any GitHub Actions workflows. Since the compute nodes may be recycled after executing a GitHub Actions workflow and pulling Docker images every time incurs a significant amount of network traffic cost as well as download time, it is necessary to pre-cache the Docker images in the node image -- this shall be implemented by pulling the necessary Docker images in the Packer script for creating EKS AMIs.

The compute nodes for the OpenStack Kubernetes clusters shall be deployed in static mode with all nodes always running. Since these compute nodes are always running and will not be recycled after executing a GitHub Actions workflow, it is not necessary to cache the Docker images used by the GitHub Actions workflows in the node image because the Docker images will be downloaded and cached during the first workflow run and will be re-used for subsequent workflow runs.

The Zephyr main and module repositories shall be directly cached under `/repo-cache` in the CI Docker image to reduce the time and network traffic to download them before executing CI jobs. Since it is not feasible to introduce this cache in the main CI image (`ghcr.io/zephyrproject-rtos/ci`), a separate CI image variant based on the main CI image, `ghcr.io/zephyrproject-rtos/ci-repo-cache`, shall be introduced.

### Runner Groups and Scale Sets

* Group: zephyr-runner-v2-linux-multiarch-4xlarge
    * Set: zephyr-runner-v2-linux-multiarch-4xlarge-x64-aws
    * Set: zephyr-runner-v2-linux-multiarch-4xlarge-x64-cnx
    * Set: zephyr-runner-v2-linux-multiarch-4xlarge-arm64-aws
    * Set: zephyr-runner-v2-linux-multiarch-4xlarge-arm64-cnx
* Group: zephyr-runner-v2-linux-x64-4xlarge
    * Set: zephyr-runner-v2-linux-x64-4xlarge-aws
    * Set: zephyr-runner-v2-linux-x64-4xlarge-cnx
* Group: zephyr-runner-v2-linux-x64-xlarge
    * Set: zephyr-runner-v2-linux-x64-xlarge-aws
    * Set: zephyr-runner-v2-linux-x64-xlarge-cnx
* Group: zephyr-runner-v2-linux-arm64-4xlarge
    * Set: zephyr-runner-v2-linux-arm64-4xlarge-aws
    * Set: zephyr-runner-v2-linux-arm64-4xlarge-cnx
* Group: zephyr-runner-v2-linux-arm64-xlarge
    * Set: zephyr-runner-v2-linux-arm64-xlarge-aws
    * Set: zephyr-runner-v2-linux-arm64-xlarge-cnx

## Tasks

- [x] Create ci-repo-cache Docker image
    - [x] Create docker-ci-repo-cache repository
    - [x] Implement CI workflow to automate ci-repo-cache Docker image build
- [x] Refactor AWS Terraform manifests
- [x] Add zephyr-runner v2 resources to AWS Terraform manifests
- [x] Add zephyr-runner v2 resources to OpenStack Terraform manifests
- [x] Update Zephyr main repository CI workflows to use zephyr-runner v2
- [x] Update Zephyr sdk-ng repository CI workflows to use zephyr-runner v2
- [x] Update any other remaining CI workflows to use zephyr-runner v2
- [x] Phase out zephyr-runner v1 deployment

**Comment by stephanosio** [comment]
**Re: OpenStack Runner Groups and Scale Sets**

It was initially proposed to create separate runner scale sets for each availability zone in the OpenStack cluster because the Horizon user interface for the OpenStack Magnum service did not provide an option to specify multiple availability zones for a cluster, and it was assumed that creating a Magnum-backed Kubernetes cluster across multiple availability zones is not supported.

This is not the case [according to the Magnum documentation](https://docs.openstack.org/magnum/2023.1/user/index.html#id5) and it should be possible to create a cross-AZ Kubernetes cluster in Magnum by creating multiple node groups with the availability zone specified in `availability_zone` label.

**Comment by stephanosio** [comment]
**Re: SELinux and Actions Runner Controller on OpenStack Magnum Kubernetes cluster**

Actions Runner Controller creates ephemeral work volumes for runners using OpenEBS, and the local PVs created by OpenEBS on Fedora Core OS, which is the OS for the OpenStack Magnum Kubernetes node deployment, may have permissions incompatible with the runner security context.

While it is possible to properly configure the SELinux policies for the OpenEBS local PV filesystem paths to work around this problem, it will require patching the OpenStack Magnum component itself and will be prone to future breakages due to upstream Fedora Core OS and Magnum changes. Moreover, this will likely not be the last thing to have problems with SELinux enforcement.

Since SELinux creates more problems than it solves in this case, [the SELinux mode will be set to `permissive`](https://docs.openstack.org/magnum/2023.1/user/index.html#selinux-mode) for OpenStack Magnum nodes.

**Comment by stephanosio** [comment]
**Re: Multi-arch Runner Scale Sets**

Ensure that the more abundant x86 nodes get scheduled first and then the ARM64 nodes are scheduled only if no more x86 nodes are available -- this can be done by using the ["node affinity"](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) feature.

```yaml
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: kubernetes.io/arch
            operator: In
            values:
            - aarch64
            - amd64
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
```

Note that `nodeSelectors` need not be specified if `requiredDuringSchedulingIgnoredDuringExecution` is used (it is basically equivalent to `nodeSelectors` with more expressive syntax).

Also note that `preferredDuringSchedulingIgnoredDuringExecution` only contributes to the weight score for determining the preferred node and does not act as a hard filter.

**Comment by stephanosio** [comment]
**Re: Deployment plan and timeline**

_To be completed before Zephyr 3.6 release_

- [x] Deploy zephyr-runner v2 on Centrinix cloud
- [x] Migrate sdk-ng repository to use zephyr-runner v2
- [x] Release new Zephyr SDK (0.16.5-1) with AArch64 binaries
- [x] Release new `ci` Docker image with AArch64 build

_After Zephyr 3.6 release_

- [x] Deploy zephyr-runner v2 on AWS
- [x] Release new `ci-repo-cache` Docker image
- [ ] Migrate zephyr repository to use zephyr-runner v2
    - [x] `main`
    - [ ] `v2.7-branch`
    - [ ] ...

_After stabilisation_

- [x] Decommission zephyr-runner v1
- [ ] Implement GitHub Actions-based fail-over sequence between AWS and Centrinix cloud
- [ ] Expand Centrinix OpenStack cluster (reconfigure decommissioned servers) and shift all CI workloads to Centrinix cloud
